# Generated by Django 2.1.7 on 2019-03-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysUsers', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_JMM',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
