# Generated by Django 2.1.7 on 2019-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysUsers', '0006_auto_20190317_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_administrator',
            new_name='administrator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_mediaManager',
            new_name='mediaManager',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Arnold', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Schwarzenegger', max_length=255),
            preserve_default=False,
        ),
    ]
