import React, { Component, Fragment } from 'react'
import { Typography, Button, FormControl, TextField } from '@material-ui/core'
// because this is a prototype, rpassword will be firstname+lastname

const style = {
  namefield: { marginRight: 7 },
  submitbutton: { width: 80, justifyContent: 'center' }

}
export class CreateAccount extends Component {

  constructor(props) {
    super(props);

    this.state = {
      errorText: "",
      email: "",
      firstname: "",
      lastname: "",

    };
  }

  validateForm() {
    return this.state.email.length > 0 && this.state.firstname.length > 0 && this.state.lastname.length > 0;
  }


  handleChange = name => event => {
    // handles the change in the value of the dropdown
    this.setState({ [name]: event.target.value });
  }

  handleSubmit = event => {
    event.preventDefault();

    if (this.validateForm) {
      this.setState({ errorText: "Missing fields" })
    } else {
      this.setState({ errorText: " " })
    }

    console.log("submit button pressed")
  }

  render() {
    return (
      <Fragment>
        <div>
          <Typography variant="h3">
            This is the create account pages
          </Typography>
          <Typography variant="h5">
            For demonstration, the password will be autogenerated and 
            will befirstname+lastname
          </Typography>
        </div>

        <form onSubmit={this.handleSubmit}>
          <FormControl required >


                <TextField
                  id="firstname"
                  label="First Name"
                  type="text"
                  autoComplete="given-name"
                  margin="normal"
                  variant="outlined"
                  onChange={this.handleChange('firstname')}
                  value={this.state.firstname}
                />

                <TextField
                  id="lastname"
                  label="Last Name"
                  type="text"
                  autoComplete="family-name"
                  margin="normal"
                  variant="outlined"
                  onChange={this.handleChange('lastname')}
                  value={this.state.lastname}
                />


            <TextField
              id="email"
              label="Email"
              type="email"
              autoComplete="email"
              margin="normal"
              variant="outlined"
              onChange={this.handleChange('email')}
              value={this.state.email}
            />


            <Button variant="contained" color="primary" type="submit" style={style.submitbutton}>
              Submit
            </Button>
            <Typography variant="body2" color="error">
              {this.state.errorText}
            </Typography>
          </FormControl>



        </form>

      </Fragment>
    )
  }
}

export default CreateAccount
