# Generated by Django 2.1.7 on 2019-03-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='SocialMediaPost',
        ),
    ]
