# Generated by Django 2.1.7 on 2019-03-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_socialmediapost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='owner',
        ),
    ]
